### ISSUE TITLE
Matreshka 2 todo

### ISSUE THREAD

**Issue by finom** [matreshkajs/matreshka#35]
As [I said before](https://github.com/matreshkajs/matreshka/issues/34), I'm rewriting everything from scratch.

**UPD**. The todo list of API methods is removed because they are already implemented. Check out [a list of changes](https://gist.github.com/finom/ff3cbc485a5fc126c9f5856d5d204d78). 
- [x] Set up a repository for distributed bundle ([here](https://github.com/matreshkajs/bundle))
- [x] Create project with binders: `file`, `dropFile`, `dragover` ([here](https://github.com/finom/matreshka-binders-file))
- [x] Create project with `randomString` function ([here](https://github.com/finom/uniquestring))
- [x] Create project with `bQuery.create` function ([here](https://github.com/finom/makeelement))
- [x] Fix linting issues
- [x] Make 95% coverage (set this rule as required)
- [x] Test methods existence
- [x] Update website, move it to matreshka.io/v2
- [x] Rewrite gh-embed script so it doesn't need any server for its work
- [x] Set up Travis CI, conventional changelog and semantic-release
- [x] Get rid of TodoMVC in Russian
- [x] Get rid of "10 reasons to try"
- [x] Update Router article
- [x] Review everything and publish 2.0.0-alpha.0
- [x] Update examples
- [x] Update TodoMVC
- [x] Write Ukrainian documentation
- [x] Update "From simple to simple" article
- [x] Update "Events" article
- [x] Update Router
- [x] Set up [Greenkeeper](https://greenkeeper.io/) for all repos of matreshka organization
- [x] Update CONTRIBUTING.md
- [x] Update README.md
- [x] Update benchmarks
- [x] Get rid of VK and Facebook communities
- [ ] Set up tests for BrowserStack 
- [x] Move new documentation to matreshka.io/ and move old documentation to matreshka.io/v1
- [x] Create a campaign on Patreon
- [x] Publish 2.0.0-beta.0
- [x] Make Twitter bot
- [x] Publish 2.0.0

Problematic things:
- [ ] Update CDNJS
- [ ] Update JSDelivr
- [ ] Update bower

Today is not possible to make it because Matreshka.js is bundled to gh-pages branch but uses tags at master.
